### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1008]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/c5b19351f6ee8f482b2e21ff7522c5b341b00b1c (chore: rename Fetch Request/Response to API (#10087))
  - [x] https://github.com/microsoft/playwright/commit/4553d76fce8fa0f7c9472009a5ccd22fb4560815 (api(frame-locator): introduce frame locators (#10102))
  - [x] https://github.com/microsoft/playwright/commit/3cc839e01327dbf5b6e2a889da8da373b7efd503 (fix(route): catch all Route methods when page closes (#10140))
  - [x] https://github.com/microsoft/playwright/commit/d25b0f70bc191b00ced9fab8dbc82310cf2c4477 (chore: api testing test nits (#10180))
  - [x] https://github.com/microsoft/playwright/commit/4e90eb9406b4a2f3e666a5f81071d7f1b0700947 (api(frame-locator): allow nth, first, last (#10195))
  - [x] https://github.com/microsoft/playwright/commit/fbb3c88f3c4f6948abfc7b347648cd80fd43fbfb (fix(fetch): smarter JSON.stringify for application/json requests (#10245))
  - [x] https://github.com/microsoft/playwright/commit/08a7470b0a562b0c9c3cbb15cfe00b50dd989703 (fix: API response to string (#10364))
  - [x] https://github.com/microsoft/playwright/commit/70ede0d9879f1eea959087356ccfb914058f5e1e (chore: use channel traits (#10389))
  - [x] https://github.com/microsoft/playwright/commit/0ca10da166efe41ba08d03db0b565b8f727fc16a (fix: compute file field mime type on the server (#10394))
  - [x] https://github.com/microsoft/playwright/commit/b3021527897a3b81b39f9e549b769ff0448410ae (chore(zones): prepare to remove wrapApiCall, introduce zones (#10427))
  - [x] https://github.com/microsoft/playwright/commit/2a98800ac0520482dfcea9a2aea010e4c75bb7ba (chore: drop wrapApiCall (1) (#10428))
  - [x] https://github.com/microsoft/playwright/commit/a73e6bbd0ee70ef104c4dfba385af1e42030d301 (chore: drop wrapApiCall (2) (#10445))
  - [x] https://github.com/microsoft/playwright/commit/9c23a78c32e166b5057f560783ac0794e4750a55 (chore: throw instead of returning error from fetch (#10451))
  - [x] https://github.com/microsoft/playwright/commit/d70e37de80f99c3fe953921abd5ad7ba1a7f1da8 (feat: locator.dragTo (#10287))
  - [x] https://github.com/microsoft/playwright/commit/41070a2f555a12bda6ac2589ca72cf0d886f989c (chore: validate client/server version match for remote connections (#10542))
  - [x] https://github.com/microsoft/playwright/commit/11cbdcf58ac97351accf5aa0d430ec0c99aa5fbb (fix(tracing): fix tracing + debugger test (#10619))
  - [ ] https://github.com/microsoft/playwright/commit/d66b7aab3b8e9c6690827c5634e5bea0edabc93a (feat(expext): toBeOK for APIResponse (#10596))
  - [x] https://github.com/microsoft/playwright/commit/31e0a63fcd99c6c5a36cbf881eac76833d31b30f (feat(toBeChecked): allow passing checked: false (#10665))
  - [x] https://github.com/microsoft/playwright/commit/f583f1604cc1d3e2f1e5b40c60d1ff061e58a01b (feat(locator.withText): allow narrowing locators to those with text (#10688))
  - [x] https://github.com/microsoft/playwright/commit/516360be5f41dc1daed0154b05281a1d9631744d (fix(waitForEvent): include timeout value in the timeout message (#10738))
  - [x] https://github.com/microsoft/playwright/commit/300a7f9b445618be7851f9946f53474341820d8a (Revert "chore: validate client/server version match for remote connections (#10542)" (#10766))
  - [x] https://github.com/microsoft/playwright/commit/fdb633dc8b86e2824e6943f5db23397215f41c83 (fix: support regexp flags with locator.withText() (#10779))
  - [x] https://github.com/microsoft/playwright/commit/4996e184bf3aa9c11c02b04ba43c6edee521885d (fix(electron): make recordVideo work (#10810))
  - [x] https://github.com/microsoft/playwright/commit/976af162b07eb9b056f83f4c0439f10d0d4aba5c (feat(tracing): pack sources to trace on the driver side (#10815))
  - [x] https://github.com/microsoft/playwright/commit/aaa8b07770baf40ff9711e45050e6887578b8285 (chore(tracing): collect source names on server (#10862))
  - [x] https://github.com/microsoft/playwright/commit/9491f6652d6b7835dade43c5c8cefdc5a8451024 (fix(steps): do not show unnecessary steps for internal waitForEventInfo (#10889))
  - [x] https://github.com/microsoft/playwright/commit/a2a8967bedc2b8959c7daee47d8969c6e01d24f9 (chore: create trace.zip in driver for local runs (#10868))
  - [x] https://github.com/microsoft/playwright/commit/67b16497cc384d8bef85bdc282539cb7037029b0 (chore: move setting PW User-Agent on connectOverCDP to the server side (#10899))
  - [x] https://github.com/microsoft/playwright/commit/04e82ce71cceda36a202a0ca9ffa3e38c7c5c096 (feat(api): make withText an option (#10922))
  - [x] https://github.com/microsoft/playwright/commit/fcccac0c08d7445fe331a9ec9ef908c78ea5cdcb (fix(tracing): return early if no trace was produced (#10953))
  - [x] https://github.com/microsoft/playwright/commit/dd5784340481d04147f101c929a15ce0e297f34f (fix(inspector): do not show internal calls (#10982))
  - [x] https://github.com/microsoft/playwright/commit/f933759ad139603a115383cee941864f853a2687 (chore(test runner): minor improvements (#11067))
  - [x] https://github.com/microsoft/playwright/commit/8e75dbffaa1eec7200c25f23cb371bd01fe20805 (fix(errors): waitForEvent/Request/Response should point to the api call (#11229))
  - [x] https://github.com/microsoft/playwright/commit/dc07fa6da6df9a97274060ede7aed51c92391339 (fix(locator.count): do not touch main workd when computing count (#11256))
  - [x] https://github.com/microsoft/playwright/commit/4efb30999fa95c7c155bac1f368f1b7d3c381438 (feat(request): show request context methods as steps (#11337))
  - [x] https://github.com/microsoft/playwright/commit/a12e76b52b7d9f2cdde555043c98088c2c9857cb (chore: implement locator._highlight / playwright._hideHighlight (#11339))
  - [x] https://github.com/microsoft/playwright/commit/a70f4e64106992879c3564ad4b352a643b98103b (fix(android): use isRegExp for a more robust check in different execution contexts (#11359))
  - [x] https://github.com/microsoft/playwright/commit/feb7148b3f4e88d8f812146bc98d645535ddd6f3 (chore: don't write into stdout from the test runner, use reporters instead (#11367))
  - [ ] https://github.com/microsoft/playwright/commit/b79daec8e04f63d32faf6130caf3207d8aec771e (chore: make it possible to override Locator.dragTo(strict) (#11457))
