### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1120]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/ab9d5a0dc4744fbfad6be2ed219b81977b6aa97d (chore(tracing): add tracing to APIRequestContext (#11502))
  - [x] https://github.com/microsoft/playwright/commit/f29a673b4c37f1c132ef180938dc20cee0211d3d (fix: do not mute route handler exceptions (#11555))
  - [x] https://github.com/microsoft/playwright/commit/4d42f6a1c4bb182dae5bf614357fc8c47d1c4527 (chore: remove unused _waitingForObject from Connection (#11474))
  - [x] https://github.com/microsoft/playwright/commit/64e7557fb9052a14b02161a9e341e7b350d5c004 (fix: falsey behavior in route.continue, page.post, testInfo.attach (#11421))
  - [x] https://github.com/microsoft/playwright/commit/800b813d4b95a6243f73d7950d5d455b23afe3c4 (chore(test runner): prepare to per-fixture timeout (#11605))
  - [x] https://github.com/microsoft/playwright/commit/687a16b848b9fa7c2a9b92e6b4a9dc96388ba0b1 (feat(locator): introduce locator.page() getter (#11630))
  - [x] https://github.com/microsoft/playwright/commit/f587a43932119fb50e3b81700b7f5eb89b266628 (feat(locator): "has" option (#11411))
  - [x] https://github.com/microsoft/playwright/commit/7912c515a32d8cebaa94c5e815d4a03366ec4e1b (fix(fixtures): account for default options being undefined (#11916))
  - [x] https://github.com/microsoft/playwright/commit/dbd124d84b734f30ad2f57256f492c72b9b58819 (chore: disable page.pause() when JS debugger is attached (#11926))
  - [x] https://github.com/microsoft/playwright/commit/9ce8572c788549f32d32b08554a17aac07feca4f (chore: don't run debugger on pause() (#11948))
  - [x] https://github.com/microsoft/playwright/commit/706c8970314a730efc71a99b3fa2446ea907626c (feat(fixtures): respect tracing config for APIRequestContext (#11954))
  - [x] https://github.com/microsoft/playwright/commit/ae7c52154fca922b0aa6bc5146c8a156d950372b (fix(fixtures): make sure connected browser respects context options (#11990))
  - [x] https://github.com/microsoft/playwright/commit/9c66068971509ef6bac5e257772077c890dfbdd3 (fix(connect): make `route.fulfill({ response })` work (#12006))
  - [x] https://github.com/microsoft/playwright/commit/66b5cf5ae1159ace3db19641334220a2f4dc55e3 (feat(remote): make PlaywrightServer work with browserType.connect (#11849))
  - [ ] https://github.com/microsoft/playwright/commit/fb00991a782bdac40c946299f5690b7fffb4b7bc (chore: intercept socks proxy in the driver (#12021))
