### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1163]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/5a0445b8dac2febe9702904d816327769e10886e (feat(remote): let client enable/disable sock proxy (#12086))
  - [x] https://github.com/microsoft/playwright/commit/363b8a697095ccd0ea0dd3a1c1ade136aa555b70 (feat: support `mask` option in screenshot methods (#12072))
  - [x] https://github.com/microsoft/playwright/commit/396d9201458a48ee37cf1e4e51acb51a23df53b1 (feat(test-runner): implement expect(pageOrLocator).toHaveScreenshot (#12242))
  - [x] https://github.com/microsoft/playwright/commit/61a6cdde704b659ba2a8e450db48127c00f64a5b (feat(api): expose locator.highlight (#12420))
