### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1186]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/fd1a1a2b1cf415c002e8850beca7f7e5ecc00092 (feat(android): Adding custom port parameter to connect to different adb server port (#12220))
  - [x] https://github.com/microsoft/playwright/commit/5fd43edcbb1ff453e68cf809d69692d1fbfc68d0 (chore: fix android tests after #12220 (#12535))
  - [ ] https://github.com/microsoft/playwright/commit/d836ed41d352c37ae263713ff3d0ff8a7937d8e3 (feat(remote): send 'x-playwright-browser' header (#12556))
  - [x] https://github.com/microsoft/playwright/commit/88610c8b4c327e9ed11c5319e20cbc7c8930db9d (fix: properly define apiName for web-first assertions (#12706))
