### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1211]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/a8d80621b22b62fcae5135860fd666f05010e927 (feat(chromium): large file uploads (#12860))
  - [x] https://github.com/microsoft/playwright/commit/91408f2c5ed4b134165efeec5b86566d8319a455 (fix(storageState): provide nice error message for storage state issues (#13019))
  - [x] https://github.com/microsoft/playwright/commit/07c1a27732997a5a418ea8ec7d3794b49df7367b (chore(deps): prepare deps for monorepo (#13057))
  - [x] https://github.com/microsoft/playwright/commit/5734c18ef8d323cf1ba7335dc41866654b95ae41 (feat(route): add cors header in route.fulfill (#12943))
  - [x] https://github.com/microsoft/playwright/commit/8758cf8cbf7532fdbb4912a97df8d285fd654557 (chore: migrate html reporter to vite (#13116))
  - [x] https://github.com/microsoft/playwright/commit/7d7fe3c618464fd6d9d01afd4e679ba336ddd1ac (fix(route): remove cors option, compare origin (#13231))
  - [x] https://github.com/microsoft/playwright/commit/b0103566c980b35fbc5c0b10f253eb8442f08062 (fix(addInitScript): tolerate trailing comments (#13275))
  - [x] https://github.com/microsoft/playwright/commit/8232497c884e16d8846c6a8585c27691969c7739 (feat(electron): expose app process(), detach on exit (#13280))
  - [x] https://github.com/microsoft/playwright/commit/1bebc28aed3a9fa63972ffa3e83e1db0aa81b938 (chore: reset page/context for reuse in component tests (#13264))
  - [x] https://github.com/microsoft/playwright/commit/a09b8dfa36284c988e36ead2f2f423b244643444 (chore: unrelease 'fonts' screenshot option (#13300))
  - [x] https://github.com/microsoft/playwright/commit/1c3db811f57b7f798dbd789fa7defb0483cb8209 (chore: move to folder-based deps lists (#13361))
  - [x] https://github.com/microsoft/playwright/commit/5ae2017a5be9d465c7777170b8c62b1a71a504bc (chore: always import type (#13365))
  - [x] https://github.com/microsoft/playwright/commit/c80365dd43e5c14589d3274199431519e73fab9b (chore: distill deps after import types update (#13367))
  - [x] https://github.com/microsoft/playwright/commit/dbafe3bb4e825b8706137c670b8b34539e14b1e1 (chore: use utils via index export (1) (#13398))
  - [x] https://github.com/microsoft/playwright/commit/40d5e3a3c9957b8d7c22dfc69c4df0789974abc3 (chore: use utils via index export (3) (#13403))
  - [x] https://github.com/microsoft/playwright/commit/a3c02222bfdad34f6d74ca0aef5a76422521e8e5 (chore: use utils via index export (4) (#13404))
  - [x] https://github.com/microsoft/playwright/commit/e79b90f45473b859a20ed6e54e61e87460df884e (chore: use utils via index export (5) (#13413))
  - [x] https://github.com/microsoft/playwright/commit/845e32cbb8b8e3809eb4f0dbc2b6a5607c715a80 (chore: use utils via index export (6) (#13417))
  - [x] https://github.com/microsoft/playwright/commit/d65263f1512d6e49aea58588578678c1b7209c32 (feat(android): allow getting webviews by socket name (#13248))
