### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1279]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/54dd6d01e5cf4847b40ded0663e8c3e6a60cd939 (feat(locator): layout options (leftOf, rightOf, above, below, near) (#13821))
  - [x] https://github.com/microsoft/playwright/commit/c3cf7ee4a72d27bd0416e811a095ead1b1349c32 (feat(layout locators): remove maxDistance option (#14013))
  - [x] https://github.com/microsoft/playwright/commit/6931d89eafb5c611113ccf1ab177f63bb0699e8c (feat(locators): rename locator.that to locator.filter (#14025))
  - [x] ~~https://github.com/microsoft/playwright/commit/a052211dbf09d4d5cd4d5283a54e5570ca481130 (chore: do not reset internal bindings for reuse (#14019))~~ (does not apply to Python, for component testing)
  - [x] https://github.com/microsoft/playwright/commit/cf89a361818b031b763910598e8d5967d2de3b6e (chore: serialize circular objects (#14045))
