### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1308]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/fe0afd6b5c2aa15c5a8e379f16b9a80add047d1b (fix(toHaveProperty): serialize falsy arguments as well (#14232))
  - [x] https://github.com/microsoft/playwright/commit/4c2fc6b6ebf865346b2153611d9e04b3f2abf3ac (feat(browser): add Browser.BrowserType() method (#14468))
  - [x] ~https://github.com/microsoft/playwright/commit/176ab7e48bb73180db3740f50e167d258546206b (chore: make LocalUtils easily available on the client (#14717))~ (maybe unneeded)
  - [x] https://github.com/microsoft/playwright/commit/fccee89b4129d421b8a43764b2ffce02ce7c4747 (feat: add Response.fromServiceWorker flag (#14715))
  - [x] https://github.com/microsoft/playwright/commit/85d03714d9d61dde41a05f7c54acae788f4f84c0 (feat: add allow/block serviceWorkers option (#14714))
  - [x] https://github.com/microsoft/playwright/pull/14724#event-6774053878
  - [x] https://github.com/microsoft/playwright/commit/c7a28ac7e9eab63b40ce22fe96597410dbd08ed7 (fix(test runner): collect artifacts when calling `browser.close()` (#14797))
  - [x] https://github.com/microsoft/playwright/commit/26e22c9a89ef61cabff736073fac9afb267c3030 (fix(types): compilation error in TypeScript 4.8 (#14847))
  - [x] https://github.com/microsoft/playwright/commit/3974d1b3591fa58b644a264e8274d7582650fac5 (revert(#14797): fix(test runner): collect artifacts when calling `browser.close()` (#14846))
  - [x] https://github.com/microsoft/playwright/commit/a1324bd935d15b78d91351a9846126b46bc5bf88 (fix(route): support route w/ async handler & times (#14317))
  - [x] https://github.com/microsoft/playwright/commit/7a568a295266ff40f92393df573fabab26a7d58f (feat(route): chain routes (#14771))
  - [x] https://github.com/microsoft/playwright/commit/dcdd3c3cdb217a86f762a3f34b7acae5b5b039a2 (feat(route): explicitly fall back to the next handler (#14834))
  - [x] https://github.com/microsoft/playwright/commit/9cf068ad061f8b134dae98c8f000fe7b1b5214f0 (feat(fallback): allow falling back w/ overrides (#14849))
  - [x] https://github.com/microsoft/playwright/commit/48f98673ef423f34d960f9641d7cc16176b6ed5c (chore: remove stray fallback overrides check)
  - [x] https://github.com/microsoft/playwright/commit/cdb862767f408fa6d364179d449f562565b4a793 (fix(page): "load" event should fire before "waitForLoadState" resolves (#14897))
  - [x] https://github.com/microsoft/playwright/commit/e00a26a11de55446fae5edc806a7236af725c3f8 (feat(route): fulfill with HARResponse (#14865))
  - [x] ~https://github.com/microsoft/playwright/commit/b8fece720462e5e5d002a0e6c22d1941ca76f0fe (chore: allow joining async handlers (#14893))~ (post 1.23 problem since we don't actually yet to the awaiting)
  - [x] https://github.com/microsoft/playwright/commit/225ab68d1c4208be9e57c8c85276e025945092bf (fix(test): fix the route test (#14890))
  - [x] https://github.com/microsoft/playwright/commit/e3da3ebfa483bf970b31c991b30d20a99e164096 (feat(har): do not expose HAR types, remove HARResponse fulfill (#14992))
  - [x] https://github.com/microsoft/playwright/commit/ae6f48c4b8bb55db693dfdfd27592d9206e0d46d (fix(route): match against updated url while chaining (#15112))
  - [x] https://github.com/microsoft/playwright/commit/fdcdd58d7fb128de2a26828eca4afa78c70047a8 (feat(har): introduce urlFilter (#14693))
  - [x] https://github.com/microsoft/playwright/commit/e975aef961055c67cc9e4a25ffb0357bdca23ff1 (feat(route): fulfill from har (#14720))
  - [x] https://github.com/microsoft/playwright/commit/7c0bff15cafb05ea3e05e1d5e2cd308ddf621138 (feat(fulfill): improve fulfilling from har (#14789))
  - [x] https://github.com/microsoft/playwright/commit/c349c1d57f6a60813aa433fcfc39e0bce4c164c5 (feat: newContext.har (#14892))
  - [x] https://github.com/microsoft/playwright/commit/245c33a5d44e6acd93b532e1166587fa716c560d (feat(har): allow storing content as separate files (#14934))
  - [x] https://github.com/microsoft/playwright/commit/be64e9ce66bdd1e5b40c79b85a77b61a0c93b00a (chore(har): attach resources for .zip hars (#14938))
  - [x] https://github.com/microsoft/playwright/commit/7bd72716f960ed11b48447c22f49a3b4ee453eb5 (feat(har): introduce the slim mode (#15053))
  - [x] https://github.com/microsoft/playwright/commit/259c8d64a5835eca503145f821953172db2333d1 (feat: Page.routeFromHar (#14870))
  - [x] https://github.com/microsoft/playwright/commit/79378dd1eba166d4ec3437c13348ebd78ca87709 (fix: add pw:api logging to har router (#14903))
  - [x] https://github.com/microsoft/playwright/commit/030e7d211cd0215c24c208713f4e71814d229335 (chore(har): allow replaying from zip har (#14962))
  - [x] https://github.com/microsoft/playwright/commit/ed6b14f0f4b58919db2f8ae7b15507768d81ad79 (fix(har): restart redirected navigation (#14939))
  - [x] https://github.com/microsoft/playwright/commit/e5372c34219ab14c2eb149983853c60982b760d7 (chore: move har router into local utils (#14967))
  - [x] https://github.com/microsoft/playwright/commit/920f1d52fccb84550c4fed3644ba21965c94d2db (chore: allow routing by uncompressed har (#14987))
  - [x] https://github.com/microsoft/playwright/commit/eb87966441f72faa0266afe4aa8d65d5e0e8bf25 (feat(har): disambiguate requests by post data (#14993))
  - [x] https://github.com/microsoft/playwright/commit/6af6fab84a52afb5dc5d69c619c58320046dd429 (fix(har): internal redirect in renderer-initiated navigations (#15000))
  - [x] https://github.com/microsoft/playwright/commit/9525bedc1f94dfb55f71f0c363b5372f7ddd0440 (feat(har): re-add routeFromHAR (#15024))
---
1.23 cut line

---
