### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1398]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/82032be36838de90c169158264de32223560950b (chore(server): validate/convert protocol both ways (#14811))
  - [x] https://github.com/microsoft/playwright/commit/6cb3236acdcaac010802c12f203ae59d8e4ec4e3 (feat(chromium): Service Worker Network Instrumentation and Inspection (#14716))
  - [x] https://github.com/microsoft/playwright/commit/4eccb89a79655b4de6e7d36c4b548ecadac2b8e3 (chore: do not serialize buffers into base64 in local mode (#15316))
  - [x] https://github.com/microsoft/playwright/commit/b9e41df0a5715ded4cdbb7a9d5a7d53defe25f5c (chore: respect event name in removeAllListeners (#15430))
  - [x] https://github.com/microsoft/playwright/commit/5fc637e44aefe7a40da52d261445d32e2051b8e7 (chore: experimental resetForReuse (#15432))
  - [x] https://github.com/microsoft/playwright/commit/8402001c3265d901b92d8aea19560ca5a750de72 (chore: remove joining emitter (#15588))
  - [x] https://github.com/microsoft/playwright/commit/e4debd0bf665ae69a6621768d17e739aef13be9a (feat(matchers): add toContainClass (#15491))
  - [x] https://github.com/microsoft/playwright/commit/3939b9f36e2fa0305e431e50d94fd32364b5df36 (chore: migrate component testing to server-side page reuse (#15477))
  - [x] https://github.com/microsoft/playwright/commit/cb81d23ad69d0f4571175dfb40ba5b48d8d8de78 (fix(selectors): max hasText regex against nested nodes (#15638))
  - [x] https://github.com/microsoft/playwright/commit/4bba41ab8feb3f972aa9d27e1adfd2c8763d98e1 (Revert "feat(matchers): add toContainClass (#15491)" (#15670))
  - [ ] https://github.com/microsoft/playwright/commit/a198b6d753d7710be55236ea31256c9518fb9cf5 (chore: reparent context objects into the object (#15689))
