### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1465]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/af8e3e7afa142975181153a0d86b602821249500 (feat: print response text when toBeOK fails (#16040))
  - [x] https://github.com/microsoft/playwright/commit/8ed238843b03bb626e7b85503c062a08826cbf55 (chore: allow inspecting element from server (#16324))
  - [x] https://github.com/microsoft/playwright/commit/1ca6635bb80f48286f48233a5e42261faa392382 (fix(cli): store trace/storage/har on SIGINT (#16339))
