### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1632]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/8432d1592fc17ee2254cf4c012256897fa589830 (chore: expose new locator apis on window.playwright (#18595))
  - [x] https://github.com/microsoft/playwright/commit/0355d8618fb1c8cb3bc7479fb8f93f0372df7836 (chore: use provided value for the generated test id (#18631))
  - [x] https://github.com/microsoft/playwright/commit/c25e67a0e797887c589f1bf02c953700623fde61 (chore: conditionally dispatch network events (#18687))
  - [x] https://github.com/microsoft/playwright/commit/7c80b77c57881e9fdd7f7c504877a9a11e589b03 (feat(clear): remove `clear()` methods from all classes except `Locator` (#18703))
  - [x] https://github.com/microsoft/playwright/commit/a7b2b04588390988df4ea18d5755dad84b02465b
