### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1687]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/412c11db208da0543137ac781e775578a72eaece (fix(reuse): make sure all dispose and close sequences are executed (#19572))
  - [x] https://github.com/microsoft/playwright/commit/d7e7cab44a28cf46e99fd9a0902a054e9088183e (fix: properly handle negated timed-out `toPass` matcher (#19580))
  - [x] https://github.com/microsoft/playwright/commit/95cc5c2a2e74bfa3437dea26395c661238876974 (fix(electron): fix the directory app path (#19601))
  - [x] https://github.com/microsoft/playwright/commit/fe989d95eb709ff436d4cace44d66acc6950abde (chore(electron): move loader to be preload (#19650))
  - [x] https://github.com/microsoft/playwright/commit/3883799d68e165567d7ea6a8636ce7c88cddbc99 (feat: introduce `locator.viewportRatio` (#19761))
  - [x] https://github.com/microsoft/playwright/commit/1afa38d5a7a8255eb4bd6e9deeea04911cf26304 (chore(expect): extract polling from expect.poll and expect().toPass (#19882))
  - [x] https://github.com/microsoft/playwright/commit/10ccfa95173f80574ce4dfd8570204e88169e30e (feat(fetch): happy eyeballs (#19902))
  - [x] https://github.com/microsoft/playwright/commit/31a63b5c2a750d8fb3d7d2184ea098f0604b1cc7 (fix(reuse): make reuse work with tracing (#19733))
  - [x] https://github.com/microsoft/playwright/commit/2a49c5e4986c2d5bc570e9199b0688c70ac48336 (feat(expect): introduce expect(locator).toIntersectViewport() (#19901))
  - [x] https://github.com/microsoft/playwright/commit/3f0adf5dd063cb0b0464d5e786379085750ec16d (chore: release from pause when the page closes (#19975))
  - [x] https://github.com/microsoft/playwright/commit/0fe327c21ba9b7369f64b148bd47279baab49566 (chore: return Promise<any> in {page,context}.route (#20005))
  - [x] https://github.com/microsoft/playwright/commit/d1c161ce99d79f7eb3b3ea279e47f7e13da4eb79 (chore: merge the util exports (#20110))
  - [x] https://github.com/microsoft/playwright/commit/1b8b20dc2576ef127f43c694a1f22e3721a587e1 (chore: drop `locator.viewportRatio()` method (#20131))
  - [x] https://github.com/microsoft/playwright/commit/d950f5b6ee3fee4b825831983d5af5b197bda769 (chore: remove toIntersectViewport for the next release (#20232))
  - [x] https://github.com/microsoft/playwright/commit/eafa6fda13bd037fb709e622051c3651cc633a0a (fix(expect): poll/toPass should not wait over specified timeout (#20266))
