### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1738]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/cab52cded9a23e15af8c0b3647754bd093f05e94 (chore: consolidate route handling logic in NetworkRouter (#20353))
  - [x] https://github.com/microsoft/playwright/commit/ead4989947462682063552cc2664c8b1022ca662 (fix(api): Response.finished() throws when target closes (#20453))
  - [x] https://github.com/microsoft/playwright/commit/d458e84f5b1f61556cbfb3e28d50f63684eca92a (feat(route): match pattern on the server side (#20410))
  - [x] https://github.com/microsoft/playwright/commit/c27ad3529904a36e5b524f014a99a8e5cde04697 (fix(locators): properly escape slash inside attributes)
  - [x] https://github.com/microsoft/playwright/commit/6ad4687f4d1d666b6c4ceadf7c88b339f2614cd6 (feat(route): add maxRedirects option to Route.fetch (#20567))
  - [x] https://github.com/microsoft/playwright/commit/68e170ef898e7f973dded1dde68114115ed82d98 (feat: implement expect(locator).toBeInViewport() (#20668))
  - [x] https://github.com/microsoft/playwright/commit/1db04f2839c73debc7be827403c7b67f26af0063 (fix: simplify protocol for toBeInViewport (#20960))
  - [x] https://github.com/microsoft/playwright/commit/ae05808f4b5eca5c35e15f6f51856c163d95838f (chore: align js routing logic with other langs (#21010))
