### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1777]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/d10fac4f6a0dfeb3577eec6cdff7ec3bdc843c01 (feat: Locator.or(locator) (#21884))
  - [x] https://github.com/microsoft/playwright/commit/d4e0ef7f1abf7ebe6d806bfee2efa46f6959aee7 (chore: explicitly send route's requestUrl for tracing (#21940))
  - [x] https://github.com/microsoft/playwright/commit/525097d465414c44a7a0b3f307ff532bac7768d5 (feat: Locator.filter(locator) (#21975))
  - [x] https://github.com/microsoft/playwright/commit/f502c72f2b688ba72b38d456523c47deedd3df55 (feat: browserContext.on('console') (#21943))
  - [x] https://github.com/microsoft/playwright/commit/3b359e27b71c9d47c8c0843d09ef9fb1a36132a0 (feat: BrowserContext.on('dialog') (#22033))
  - [x] https://github.com/microsoft/playwright/commit/6929214dbf895cd961175c17d1616271f7fc72b3 (feat(expect): expect(locator).toBeAttached() (#22067))
  - [x] https://github.com/microsoft/playwright/commit/e6148bb725db6648d033ade239f485274849ec63 (feat: Locator.not(locator) (#22066))
  - [x] https://github.com/microsoft/playwright/commit/539d9873c2f3235928106751c2301d91b3b6d628 (feat: rename Locator.filter(locator) to Locator.and (#22101))
  - [x] https://github.com/microsoft/playwright/commit/37d165950809d37e0a3fec48034fd239b577b3e8 (feat(connect): support special headers for debug/attachments (#22106))
  - [x] https://github.com/microsoft/playwright/commit/5223c1ba39114dec5b0baf9ec17800cea612f9ce (feat: add timeout to `electron.firstWindow()` method (#21863))
  - [x] https://github.com/microsoft/playwright/commit/0d9ec60dc7e52bc3f77e4f032da3cd30216b2ef7 (chore: implement jsHandle._objectCount in chromium (#22127))
  - [x] https://github.com/microsoft/playwright/commit/d7b3836752fbb996a4eb7dd6e36c3970912ac2e4 (chore: revert console and dialog events on BrowserContext (#22195))
  - [x] https://github.com/microsoft/playwright/commit/bc1de5f28dd2ebc4dc1cf090f12b7ab3a8ae45a9 (feat(locator): filter({ hasNot }) (#22219))
  - [x] https://github.com/microsoft/playwright/commit/35afb056ea0136d65f03357238b66c6fa6650dbd (feat(locator): filter({ hasNotText }) (#22222))
  - [x] https://github.com/microsoft/playwright/commit/08cef43e829f1ba3512641f664a402ada005d19e (feat(locator): remove locator.and and locator.not (#22223))
  - [x] https://github.com/microsoft/playwright/commit/a42567d549b03d477611dcf8fc6dfc77098aab26 (chore: inside out the config & project internal (#22260))
  - [x] https://github.com/microsoft/playwright/commit/c5aeab4d7e88d2f7e2868776152df79401eebf4c (revert(20509, 20596): expect.toPass is broken with these (#22254))
  - [ ] https://github.com/microsoft/playwright/commit/c5aeab4d7e88d2f7e2868776152df79401eebf4c (revert(20509, 20596): expect.toPass is broken with these (#22254))
  - [ ] https://github.com/microsoft/playwright/commit/c5aeab4d7e88d2f7e2868776152df79401eebf4c (revert(20509, 20596): expect.toPass is broken with these (#22254))
