### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1865]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/9f661b710a970fd0da61fc08dac2812a7896b6d6 (chore: bump the trace packet size to be 1Mb (#22446))
  - [x] https://github.com/microsoft/playwright/commit/e7b9c088334e5a5931a119b109a4fe4759c409ea (chore: should not spill toPass between tests (#22473))
  - [x] https://github.com/microsoft/playwright/commit/106fa45f50e9bf4dd1b7060d923773d69e576475 (feat(route): accept timeout to fetch (#22475))
