### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1885]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/e9373dfb6e0a081878e47348be4ba328d72e5464 (chore: make client-side instrumentation non-nullable (#22694))
  - [x] https://github.com/microsoft/playwright/commit/ffc00566b903e0948a6a5268ed032ebee6e7f4ee (chore: separate options fixture vs artifacts fixture (#22713))
  - [x] https://github.com/microsoft/playwright/commit/116fb349ce0ce88c54a1328817763cf1ee075d41 (chore: allow configuring test id attribute for codegen (#22716))
  - [x] https://github.com/microsoft/playwright/commit/236c329ea9eaf5fa2a9bb2b586c7061e2a501989 (feat: browserContext.on('dialog'/'console') (#22805))
  - [x] https://github.com/microsoft/playwright/commit/42328478eac6057d739eb9643e74b243a359d4bb (feat: make console/dialog events based on subscription  (#22835))
  - [x] https://github.com/microsoft/playwright/commit/160888df9925002ec01fdc167f46187c588abbbb (feat(locators): reland `locator.and(locator)` (#22850))
  - [x] https://github.com/microsoft/playwright/commit/efad19b33213b913e44b8d437904aae0b0540a09 (chore: render test steps in the trace (#22837))
  - [x] https://github.com/microsoft/playwright/commit/fec5059fee40377c98500cbe500a767497c86192 (feat(connect): print debug log when remote connection failed (#23069))
