### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1945]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/2710fd8d6fb14b7a9f549b2f7820b73c28ab9269 (fix: should be able to upload multiple large files (#23360))
  - [x] https://github.com/microsoft/playwright/commit/84942aa99233edd80926d01e1ff82de0190408fc (chore: render successful toPass as such (#23411))
  - [x] https://github.com/microsoft/playwright/commit/def24c0a1454d19661332d364295dc359c40bab9 (chore: propagate client-side instrumentation across connect (#23524))
  - [x] https://github.com/microsoft/playwright/commit/7579572688f43931c461ae76a9a006fbb2e86662 (chore: unflake the network status test (#23551))
  - [x] https://github.com/microsoft/playwright/commit/4f8680f7a39347e033631aaa6010998ad8eddbce (fix(pause): revert timeouts after pause (#23578))
