### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#1986]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/fbb5d482838334ef36bb83189e0408a922a9c7c7 (feat(expect): roll to v29.5.0 (#23629))
  - [x] https://github.com/microsoft/playwright/commit/1ab99fe1b8fc1d619a632328288254f264cd6421 (feat(electron): support tracesDir option (#23947))
  - [x] https://github.com/microsoft/playwright/pull/23932
  - [x] https://github.com/microsoft/playwright/commit/566b277ce879c7eaa38e4cc50aa086436bde8a89 (fix(steps): only propagate soft errors up the hierarchy (#24054))
  - [x] https://github.com/microsoft/playwright/commit/76d85c55cf69c2f8230dc3404efb36c6342085ed (chore: remove unused code (#24167))
  - [x] https://github.com/microsoft/playwright/commit/a0b0752662f8af5f841ff7a65b04d02066474ff2 (fix: encode launch options correctly when reusing browser (#24174))
