### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2014]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/97d55e275dd26317651763128975b7b708475030 (fix(locator): `locator(locator)` method uses `internal:chain` instead of `>>` (#24235))
  - [x] https://github.com/microsoft/playwright/commit/879ddb73b063e9ff97654b4e3d92969f84f201c8 (chore: show last poller error on test timeout (#24292))
  - [x] https://github.com/microsoft/playwright/commit/2cb0622c39fdc77c102644cc43f0d2222513463a (chore: rename ScopedRace to LongStandingScope, preserve Error instance in reject() (#24361))
  - [x] https://github.com/microsoft/playwright/pull/24371
  - [x] https://github.com/microsoft/playwright/commit/4949cef09cfdae1c9f64eee977fcf777bc3c6621 (chore: save chrome trace on the client side (#24414))
  - [x] https://github.com/microsoft/playwright/commit/ea6d127f28f46e4f299e7aa2458e4f868db4cb2a (feat(connect): exposeNetwork option (#24436))
