### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2048]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/75ed251c9e75e869ad7f8304fbe4240dd952b17e (fix: download of attachments in UI Mode (#26407))
  - [x] https://github.com/microsoft/playwright/commit/adc9b2d39025af39c741bd0deef9f884d6473dae (feat: add support for browserContext.on('pageerror') (#24452))
  - [x] https://github.com/microsoft/playwright/commit/f83d81956d2faa7bf7931101fc605071fcd14141 (chore: make console stream live in ui mode (#26562))
  - [x] https://github.com/microsoft/playwright/commit/72bdd43e699cb2228e0a4195c9a31ede68da6b0b (fix(route): make sure Route.fetch works for popup main request (#26590))
  - [x] https://github.com/microsoft/playwright/commit/5646875e5c9cc63ba25e25e6c005d7bb99ee4ff6 (fix: make Request.frame throw when page is not ready yet (#26616))
  - [x] https://github.com/microsoft/playwright/commit/c4e79eb6ed04f9e9212c06ef7295ba8c717fcb00 (feat: replace Locator.type with Locator.pressSequentially (#26624))
  - [x] https://github.com/microsoft/playwright/commit/6d85ba14947348c5d857eb951102f331a2fe6143 (fix: remove connectInsteadOfLaunching (#26828))
