### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2078]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/9fe037fb63a87844e94bc4111d1a0717b22f4623 (chore: populate matcherResult in web assertions (#27133))
  - [x] https://github.com/microsoft/playwright/commit/bb4268d165fa3df300d40569fc90ab919b5ff0ba (fix(locators): do not escape regular expressions with u or v flag (#27188))
  - [x] https://github.com/microsoft/playwright/commit/287d720b8e541868e1e6fb3e0fb432f8a2bcd26b (chore: remove dedicated console channel (#27234))
  - [x] https://github.com/microsoft/playwright/commit/ffd20f43f8ee1a7a016cd9b29c372e25ec685a62 (chore: dispose stale handles to prevent oom, 1000 of a kind max (#27315))
  - [x] https://github.com/microsoft/playwright/commit/81694b7401c458964431c0b202bca99d5cfcb059 (test: unflake some tests (#27354))
  - [x] https://github.com/microsoft/playwright/commit/ac48a47d33455c83c2d62f9959b05fe69820456e (feat: toHaveAttribute without value (#27418))
  - [x] https://github.com/microsoft/playwright/commit/045e8aa3681de0a5dd732e9e19632adf6dd1f5df (chore: move `devices` from `Playwright` to `LocalUtils` (#27437))
  - [x] https://github.com/microsoft/playwright/commit/dcc8dcca739ac0032c69194bb3a133fc66e3da36 (Fix various typos (Fixes #27396) (#27391))
  - [x] https://github.com/microsoft/playwright/commit/ae5610f5c1e18240257e5d092d3ee91c41a5e328 (chore: include full messages into `pw:channel` logs (#27488))
  - [x] https://github.com/microsoft/playwright/commit/11a4b3f7f55b0681a69140c1f255c34746adaa89 (chore: remove parsed stack trace (#27496))
  - [x] https://github.com/microsoft/playwright/commit/fd6bf8aa2c7a34e97c8b97d98953411ca74f88c2 (chrome: improve error messages on vscode side (#27521))

---

Roll 1:

  - [x] https://github.com/microsoft/playwright/commit/f212fd1a8318345147c7357ced36db21acd477a0 (chore: unify target closed errors (#27540))
  - [x] https://github.com/microsoft/playwright/commit/f8a30fb726bc35d4058a2d010b2ed5f6ca2409a3 (chore: follow up to target close message)
  - [x] https://github.com/microsoft/playwright/commit/4e845e7b1dc1f18511eae105e6dea9cce942bd28 (fix(fetch): JSON.stringify on client (#27644))
  - [x] https://github.com/microsoft/playwright/commit/a54dbfdadf82d5bc201f816a419604557a207611 (chore: plumb the target close reason when test fails (#27640))
  - [x] https://github.com/microsoft/playwright/commit/d4296dbff45d80b210f97a6718051800b5d846f2 (chore: break dowload.path() to throw (#27662))
  - [x] https://github.com/microsoft/playwright/commit/091f6883f5524c876022c77b4fdc52b583b4c7cb (chore: remove the usages of raw target closed message constant (#27669))

---

  - [x] https://github.com/microsoft/playwright/commit/3aa147914c5eafdf5a4ecc61d791e4a7deb920d4 (chore: split error to client and server sides (#27672))
  - [x] https://github.com/microsoft/playwright/commit/bd58c0d5d2f459f5c8ed1e370de8a4ce458a5c91 (fix: preserve lastModified timestamp in setInputFiles (#27671))
  - [x] https://github.com/microsoft/playwright/commit/6fe31ab52c39aa7176c673215caa7a6437d996e9 (feat: support alternative quotes in js parseLocator() (#27718))
  - [x] https://github.com/microsoft/playwright/commit/f48861ddeeb3ea7d46e485836c7320980c537bdd (fix(inspector): highlight xpath/css locators without engine prefix (#27742))
  - [x] https://github.com/microsoft/playwright/commit/7de0ccd36e5ed796ef1cb866d07a17fea57df746 (chore: support await using for close() and dispose() (#27766))
  - [x] https://github.com/microsoft/playwright/commit/0ade5aa9adac16112d82c5ca522ab9abcad6d166 (fix: ignoreCase in toHaveAttribute (#27809))
  - [x] https://github.com/microsoft/playwright/commit/88f30d1ce2e67b569c7110e3ecd000319f92ea28 (feat: support firefoxUserPrefs in launchPersistentContext (#27840))
  - [x] https://github.com/microsoft/playwright/commit/100d3b260171746cf6012a035535731c08ce19f0 (fix(css parser): support nested builtin functions (#27841))
  - [x] https://github.com/microsoft/playwright/commit/59b8cf008e0f3e98936cfeb7776d0a0eda4b22da (fix(codegen): don't generate page.frame() calls anymore (#27820))
  - [x] https://github.com/microsoft/playwright/commit/36c4c24f8a2e073737ae1a0ae4aa5cb42186b669 (fix: only convert input files for browser collocated with server (#27873))
  - [x] https://github.com/microsoft/playwright/commit/5f527fedb1f6893219b69d735b1a9cdd81ad1466 (fix: JSHandle preview text for non-ascii attributes/children (#28038))
  - [ ] https://github.com/microsoft/playwright/commit/62b6af3a7f67b08e6588699a49753b7ed3f1e3df (fix(android): respect recordHar option (#28046))
  - [x] https://github.com/microsoft/playwright/commit/fae5dd898a523d61017a8a263f84dd415ab30e5d (chore: remove from client check if browser is co-located with server (#28071))
  - [x] https://github.com/microsoft/playwright/commit/5488c03d7f508737d65a4a932f06aec93969b6c4 (chore: make `asLocator()` always safe (#28207))
