### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2176]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/15a8ba515826aab095fc48f4cba2a2bb0c2182fa (fix(route): correctly remove expired handlers (#28385))
  - [x] https://github.com/microsoft/playwright/commit/92a0d24069c2f43ecec89ac9528ff47577273b9d (fix: restore timeout error name (#28408))
  - [x] https://github.com/microsoft/playwright/commit/74e51d334e7bf7462ebce4330817b369d1a9b87e (feat: wait for active route handlers on page/context close (#28414))
  - [x] https://github.com/microsoft/playwright/commit/8f056fbbcebe4dd1f1dcedebb43870b81cc475d1 (chore: do not wait for route on close if route.continue() threw an error (#28487))
  - [x] https://github.com/microsoft/playwright/commit/2d2c270388a5c8fb826ea0c604501fba9a1ab68b (chore: mark outofprocess connection not as remote (#28156))
  - [x] https://github.com/microsoft/playwright/commit/736c0efd43e4b03c880f997caacaa6f4f43afe3d (chore: use more explicit awaits when returning in client (#28443))
  - [x] https://github.com/microsoft/playwright/commit/afe90d648e94f37dc0c4b7945c029214a0bee741 (fix: do not generate api call steps inside named expects (#28609))
  - [x] https://github.com/microsoft/playwright/commit/9b2585cd4ef802bc01d4183dd708e127cf62773a (fix: 'should collect trace with resources, but no js' test in service mode (#28628))
  - [x] https://github.com/microsoft/playwright/commit/f28ceffa376adc60a915a5eb95e06a4059443909 (feat: page.unrouteAll and context.unrouteAll (#28635))
  - [x] https://github.com/microsoft/playwright/commit/d89837c58e514e190023ddd76b48e7401032596b (chore: revert noWaitForFinish option, page.close does not wait for ro… (#28658))
  - [x] https://github.com/microsoft/playwright/commit/6bd61cd8c6af7c695474b1ec578cafe2385e49b1 (docs: Improve clarity on toHaveText and toContainText assertions (#28623))
  - [x] https://github.com/microsoft/playwright/commit/c5097a500d68edfc7439d8efe6276ac2a944ff3f (docs: add java/csharp code snippets for FormData (#28951))
  - [x] https://github.com/microsoft/playwright/commit/90665ef05696438b3da68dd8e335af7273745e9c (docs: update auto-waiting doc (#28960))
  - [ ] https://github.com/microsoft/playwright/commit/4c0a972b6986eb998fff65a650dd5f3122506fb2 (feat(expect): Make toPass's option configurable by TestConfig (#28231))
