### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2246]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/d023829dd543c0ced528a60a0365327c39c6e419 (fix(locator parser): allow escaped quotes in the digest function (#29012))
  - [x] https://github.com/microsoft/playwright/commit/f3fac6f4e95f0818a47c88c055854576d98103e0 (feat: `page.handleLocator` that closes any interstitial pages/dialogs (#29029))
  - [x] https://github.com/microsoft/playwright/commit/d89ed88679cbbd27c92f576b8e08b9b5050ac7d7 (docs: do not recommend PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD anymore (#29121))
  - [x] https://github.com/microsoft/playwright/commit/3e2d5b2800e3143280c0573507b1ba9d5c438a00 (docs: add an example of how to use "+" key as part of a shortcut (#29221))
  - [x] https://github.com/microsoft/playwright/commit/c85308d717b757f2e9a4616b3131e725e1a0c8fb (chore: remove deprecated debug controller events (#29203))
  - [x] https://github.com/microsoft/playwright/commit/13550b7329c428063b95663c979c241c27b32656 (fix: add new line before sourceURL (#29199))
  - [x] https://github.com/microsoft/playwright/commit/aff6cf3c83d5567ec2c662eebdc246090df39982 (chore: extract ws server util (#29247))
  - [x] https://github.com/microsoft/playwright/commit/47f8ba2a040c8383a472b4c27bf392b899fcfde6 (feat(electron): expose ElectronApplication console events (#29322))
  - [x] https://github.com/microsoft/playwright/commit/20699c36ba82c5d65993c70fc4ed12141059513b (chore: simplify types handling in toHaveScreenshot (#29374))
  - [x] https://github.com/microsoft/playwright/commit/721d84f17a0e3b906fc1c5dd91d6932073342072 (fix(har): do not throw on -1 status code (#29371))
  - [x] https://github.com/microsoft/playwright/commit/61955e55b1884b778e256687a85f7cd44c3fcdc4 (fix(handleLocator): address API review feedback (#29412))
  - [x] https://github.com/microsoft/playwright/commit/f0244b8a7640ef1e0abf5588dc9780cca8bcd715 (chore: rename handleLocator to addLocatorHandler (#29443))
  - [x] https://github.com/microsoft/playwright/commit/30557ed28c9f89ab1a4329e0e55f187717f1ce24 (fix(electron): stalling on delayed process close (#29431))
  - [x] https://github.com/microsoft/playwright/commit/ce5d970929dc24619b864c23d2e9b18b6fa6d899 (docs: make sure to await route.* methods (#29489))
  - [x] https://github.com/microsoft/playwright/commit/edc1c13f3125bdc7266d5165d4b627d04e47ce80 (docs: locator handler type should be Runnable in java (#29503))
  - [x] https://github.com/microsoft/playwright/commit/b11b118e02f63097f7717ce960d71742adaa4dac (feat(chromium): expose parameters to generate outline / tagged PDF (#29494))
  - [x] https://github.com/microsoft/playwright/commit/f3fde992eb5ce8a35afd99158928e06d8a47f322 (chore: remove --project-grep, add wildcard support (#29537))
  - [ ] https://github.com/microsoft/playwright/commit/adccd39b013af6d9494143df5ad38bb3a09a361a (docs(dotnet): type specific addLocatorHandler handler (#29586))
