### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2328]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/9d0430fa265dcb0e3d844c42e3ee589dfa81989e (chore: strengthen linting (#29669))
  - [x] https://github.com/microsoft/playwright/commit/ba3d887660dfc8dd3ff3412b0151576e196e763a (docs: improve addLocatorHandler docs (#29770))
  - [x] https://github.com/microsoft/playwright/commit/8e48ee714d0093eb6c1c8ee1fe24353320b42a34 (feat(playwright-core): add remove cookies api (#29698))
  - [x] https://github.com/microsoft/playwright/commit/d125ff4d39f521a335959af80f19918a3fa98c18 (docs: fix inconsistent .NET snippets (#29831))
  - [x] https://github.com/microsoft/playwright/commit/38fc74db7c24398095632fa2e65e913c80df99f4 (fix: postDataJSON with application/x-www-form-urlencoded; charset=UTF-8 (#29889))
  - [x] https://github.com/microsoft/playwright/commit/78b8aed4bda94a8ad3b84b6fa0ac245321169af4 (docs: mark addLocatorHandler as experimental (#29909))
  - [x] https://github.com/microsoft/playwright/commit/b158e4ef96785938e3b3e7d5e750ce557beb6297 (fix: postDataJSON without Content-Type header (#29918))
  - [x] https://github.com/microsoft/playwright/commit/5bc6ca6345660e23f47e1964319713948dd89616 (fix: allow disposing ElementHandles multiple times (#29953))
  - [x] https://github.com/microsoft/playwright/commit/5d0c61fa0ca5385821b72b71652fd7ebc3c37cb1 (docs: fix logger API usage (#29961))
  - [x] https://github.com/microsoft/playwright/commit/70e6cdac5753b0d5e89864fcdc65d130d39c06f9 (feat: enterFrame/exitFrame (#29992))
  - [x] https://github.com/microsoft/playwright/commit/da2b099b5c505b280aff338ff23dbea25dbd5e94 (docs: note on locator handler trigger (#30004))
  - [x] https://github.com/microsoft/playwright/commit/9d40f619c4b683e961b49a677a63e207d3d66e76 (feat: deprecate "devtools" launch option (#30025))
  - [x] https://github.com/microsoft/playwright/commit/95d649b406006f950f9a265ec061fdcf435d10a2 (feat: address api review feedback for 1.43 (#30066))
  - [x] https://github.com/microsoft/playwright/commit/f5823786fd7d0a79346fd0d0407d9ac75b2722c3 (docs: migrate to newer :::warning syntax (#30089))
  - [x] https://github.com/microsoft/playwright/commit/4b3c596874156ac4c75c270466ab2c08e3d7132c (docs(fetch): multiple fields with the same name in java and .net (#30105))
  - [x] https://github.com/microsoft/playwright/commit/a849ea97411714d50cda0a0d5c156decbdc2d814 (feat(fetch): multiple fields with the same name in post data (#30104))
  - [x] https://github.com/microsoft/playwright/commit/2de8a6b0028f20958d867ba4097970a9e746b690 (chore: move filter params into the clearCookies (#30111))
  - [x] https://github.com/microsoft/playwright/commit/021c5c108c6a1166c1d2b701aafb9f021fe0cfca (chore: revert support of duplicate form data fields in multipart post data (#30127))
