### ISSUE TITLE
[Ports]: Backport client side changes for 1.45

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2455]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/d5b387159aa580203753d7a2a533fc9e8ceb7064 (feat(fetch): sendImmediately (#30627))
  - [x] https://github.com/microsoft/playwright/commit/776b04e5ea1f2adcc82d9459cf593775662ef3e3 (feat: APIRequestContext dispose reason (#30765))
  - [ ] https://github.com/microsoft/playwright/commit/fb319e6d3d6f761a351d2a98b3bd208103a0fdfb (fix: match client step and server action by explicit stepId (#30641))
  - [x] https://github.com/microsoft/playwright/commit/042896472b8ae233437d9e3e937cdae9fdce954b (fix: route.continue should not change multipart form data body (#30863))
  - [x] https://github.com/microsoft/playwright/commit/e7a11c0ca22881623b073f2540c21b5d2da24085 (fix: propagate close reason to api context (#30945))
  - [x] https://github.com/microsoft/playwright/commit/5b00ce15943f3227d7f25c923ed266b0c22ec28c (docs: fix typo in ConsoleMessage class (#30857))
  - [x] https://github.com/microsoft/playwright/commit/964fe66ccc4e705c519d0a58578be0085d1af6fc (chore: hint at unroute for handle errors (#30949))
  - [x] https://github.com/microsoft/playwright/commit/9884c851ffbccdd62fce39d49c7f586ba5a304b4 (feat(expect): expose expect timeout (#30969))
  - [x] https://github.com/microsoft/playwright/commit/a7599ad509ab1f66b14239727f3156d9cfcebca4 (feat(api): add host option in launchServer options (#30999))
  - [x] https://github.com/microsoft/playwright/commit/9884c851ffbccdd62fce39d49c7f586ba5a304b4 (feat(expect): expose expect timeout (#30969))
   - [x] https://github.com/microsoft/playwright/commit/ba5b46044469b783b64c94b9986460c38e020c77 chore: move artifacts recording to TestLifecycleInstrumentation (https://github.com/microsoft/playwright/pull/30935)
  - [x] https://github.com/microsoft/playwright/commit/170c457a61d15d2d42cdd2860e6dd76ecedea4ce feat(timers): a stab at fake timers (https://github.com/microsoft/playwright/pull/31075)
  - [x] https://github.com/microsoft/playwright/commit/6067b78f88680c38f7e73c2f9abc498e8fb5dd3d (chore: http credentials send immeidately/unauthorized enum (#31076))
  - [x] https://github.com/microsoft/playwright/commit/f97d87ea5ac6567c6b9010a9ddbb4c563cc1fb46 (docs: fix the api review typos (#31071))
  - [x] https://github.com/microsoft/playwright/commit/76e977a934ccf96c6e7236f9e33e2c2dd8afff42 (chore: add clock.next() (#31097))
  - [x] https://github.com/microsoft/playwright/commit/8bfd0eb6e4188985c6a5f0ad57306eda10a37266 (chore: introduce clock test mode (#31110))
  - [x] https://github.com/microsoft/playwright/commit/fc6c67f5f9a1fb64fa8497c4116df5fdc4539001 (docs: start adding clock docs (#31111))
  - [x] https://github.com/microsoft/playwright/commit/8d2f4c14333b33b3c112ed95293ddb51a2e10e75 (docs: iterate over the clock dock)
  - [x] https://github.com/microsoft/playwright/commit/8d0def190ddcc88842811f8623cf7c8fb5e83ccc (docs: iterate over the clock (2))
  - [x] https://github.com/microsoft/playwright/commit/c516ba0ec85b1789895afb0a9ac8a336ce782171 (api(clock): rework api based on the review (#31137))
  - [x] https://github.com/microsoft/playwright/commit/76b25e84cc90fc8dd1b8df714ed8dd5b286a1a53 (docs: Improve clock doc (#31147))
  - [x] https://github.com/microsoft/playwright/commit/826343b8a032eddb5e4a492625b0c35ec50ef775 (chore: rename fakeTimers to clock (#31193))
  - [x] https://github.com/microsoft/playwright/commit/f95b4e0ac83edae3882aab777c746cfa5149d96d (docs(dotnet): recommend MSTest over NUnit (#31245))
  - [x] https://github.com/microsoft/playwright/commit/c08000b967c8040271c02a931b161639a0ddeb5a (feat(chromium): storage-access permission (#31239))
  - [x] https://github.com/microsoft/playwright/commit/6399e8de4e35730a54421e420283ff58d4180963 (chore: clock api review (#31237))
  - [x] https://github.com/microsoft/playwright/commit/2b257ea963eb4dc918659fc6c688e45a7fb8e007 (chore(clock): introduce pauseAt (#31255))
  - [x] https://github.com/microsoft/playwright/commit/dcf4e4e0542bd94d33d5ff8ac75d2101c220206f (feat: allow folder uploads (#31165))
  - [x] https://github.com/microsoft/playwright/commit/a76e5824c00f8314bce5a5faa782264dc80eabb6 (docs: examples for file directory upload (#31302))
