### ISSUE TITLE
[Ports]: Backport client side changes for 1.46

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2465]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/2a7f17d82061b353deb1dc28dc36856e8b730b1c (chore: fix simulated clock bots (#31301))
  - [x] https://github.com/microsoft/playwright/commit/9e6772818e7c50a132cbe6ccc775cda4a3e3eba4 (chore: cache normalized whitespaces in recorder (#31349))
  - [x] https://github.com/microsoft/playwright/commit/5fc56283a6f3df8f74db6f7b936ca48bb4a86017 (fix(clock): throw for invalid date (#31356))
  - [x] https://github.com/microsoft/playwright/commit/f6972c1e23d611359a007fb6fd521dea5cc0e581 (docs: use long for time in milliseconds (#31369))
  - [x] https://github.com/microsoft/playwright/commit/95fc2b8a8b449560e53999c866e9602f4bca27f1 (feat(fetch): maxRetries for fetch (#31386))
  - [x] https://github.com/microsoft/playwright/commit/865f0d822138303eee39070d723878585926e7d7 (docs(java): correctly parse time (#31420))
  - [x] https://github.com/microsoft/playwright/commit/114b6f0de6d43833f19df70ee842c9cb88595294 (docs: deprecate `handle` option in `exposeBinding` (#31419))
  - [x] https://github.com/microsoft/playwright/commit/111876d52619ea662d691f68552ba44ef757224b (docs: improve addCookies.cookie parameter description (#31456))
  - [x] https://github.com/microsoft/playwright/commit/a3e31fd2c4146e67a63ff4d3dc4f655533adcbde (feat: introduce touchscreen.touch() for dispatching raw touch events (#31457))
  - [x] https://github.com/microsoft/playwright/commit/f46ae15500df6776b2b8ee29ddca37007e27f621 (test(clock): fix clock mode bots (#31472))
  - [x] https://github.com/microsoft/playwright/commit/9dc7e400849e26226a14084524e53900d7a08661 (chore(electron): don't swallow close errors (#31509))
  - [x] https://github.com/microsoft/playwright/commit/2b974f2139e0eb15644fb4c8e2d52fa0ba583025 (docs(clock): update time types in Python/.NET (#31511))
  - [x] https://github.com/microsoft/playwright/commit/1132667ffef9d1db585b3496d0b2c713c346261d (chore: bump TypeScript to v5.5 (#31532))
  - [x] https://github.com/microsoft/playwright/commit/bc27ca225e69995f238192426df4ccb3f940a50d (feat(trace): record trace upon browser closure (#31563))
  - [x] https://github.com/microsoft/playwright/commit/00131c1e3fb9c524b2b2b4496ebebcabf46b326e (feat(trace-viewer): display text attachments in ui mode (#31215))
  - [x] https://github.com/microsoft/playwright/commit/5c8fe5c33c9a2f6a2ef5692e0c09332b49c15d29 (docs: make x/y more clear (#31606))
  - [x] https://github.com/microsoft/playwright/commit/9569cb5c1e5c01c7d4f3246875d778fe1421c84d (feat: support client certificates (#31529))
  - [x] https://github.com/microsoft/playwright/commit/074cc7d467102bbc750622052454ed26b5bb8d30 (Revert "feat(trace): record trace upon browser closure (#31563)" (#31677))
  - [x] https://github.com/microsoft/playwright/commit/1686e5174db39599a0adac7c2001d93a21f2a0aa (chore: allow evaluating Error objects (#31691))
  - [x] https://github.com/microsoft/playwright/commit/6ee8f1de2ddf124277179973d0ca93f38681a8cb (Revert "chore: move artifacts recording to TestLifecycleInstrumentation (#30935)" (#31686))
  - [x] https://github.com/microsoft/playwright/commit/0aa2f06f68959e2515f62ea9bb570cf1815230b2 (fix: add 'window-management' to chromium browser (#31687))
  - [ ] https://github.com/microsoft/playwright/commit/e11c0c0cbb177fbf4fd208f181b99ba5f6109f9e (fix(connect): annotate internal api calls correctly (#31715))
  - [x] https://github.com/microsoft/playwright/commit/6491e5b415a7abc72706450f463286277db7fd1f (chore: deprecate/remove noWaitAfter from some actions (#31739))
  - [x] https://github.com/microsoft/playwright/commit/7abbbd0c84a196052c1342cd1de9287c2628a1d5 (docs: spelling (#31779))
  - [x] https://github.com/microsoft/playwright/commit/e269092ef9dd71567bbd100f5df29850f1343c7e (Revert "fix: add 'window-management' to chromium browser (#31687)" (#31801))
  - [x] https://github.com/microsoft/playwright/commit/2cc4e14756b985debb45fb59566f74c09b32440e (fix(core): update maxRetries docs (#31810))
  - [x] https://github.com/microsoft/playwright/commit/383e4b3c73859636b750e6f73d6f3d0c8ec17d6b (Revert "feat: introduce touchscreen.touch() for dispatching raw touch… (#31823))
  - [x] https://github.com/microsoft/playwright/commit/c4862c022c46280b9f004c0a1f190f97256096d1 (chore: client certificates api review (#31826))
  - [x] https://github.com/microsoft/playwright/commit/7570c25b3da02b94e8d72ba5843a6f116e8197c4 (chore: remove glob from client-certificate matching (#31846))
  - [ ] https://github.com/microsoft/playwright/commit/d8d5289e8692c9b1265d23ee66988d1ac5122f33 (fix(remote): make sure api calls reject before browser is closed (#31858))
