### ISSUE TITLE
[Ports]: Backport client side changes for 1.47

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2497]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/f45cf659215e97f921add54f6de44cbc171ab303 (chore: add maxRetries to APIRequestContext.delete (#31893))
  - [x] https://github.com/microsoft/playwright/commit/58b0c76f2068417279fdb6acc34fe8db38c19c16 (chore: use soft event emitter (#31868))
  - [x] https://github.com/microsoft/playwright/commit/55187207e43462ea5b89de4675cca98bb893423d (chore: various roll fixes for .NET (#31914))
  - [x] https://github.com/microsoft/playwright/commit/613ccb8d5b8aca5a51c73dbbdce8afcadf6a8add (chore(client-certificates): rewrite error for unsupported PFX errors (#32008))
  - [x] https://github.com/microsoft/playwright/commit/193013c9ee40185aca8d6ee0cbddd8abcc4ed7d9 (docs(har): default update mode is minimal (#32016))
  - [x] https://github.com/microsoft/playwright/commit/3c87f217df293119964fe42e532e638dd9e17073 (feat(events): allow waiting for removeAllListeners (#31941))
  - [x] https://github.com/microsoft/playwright/commit/43e852334b451c34336d2dafe104831a836a0866 (docs: route.fallback() vs. route.continue() (#32035))
  - [x] https://github.com/microsoft/playwright/commit/2ae196f7080d79df352400b36cec8d0344fb7570 (fix(docs): API types do not extend EventEmitter (#32124))
  - [x] https://github.com/microsoft/playwright/commit/308381eeae85cb7b260758f5b359dcf20b9105bf (feat: allow `URLSearchParams` and `string` as params in `APIRequestContext` (#32120))
  - [x] https://github.com/microsoft/playwright/commit/b7ed4d7b9e433f1be414c6e580a0ddc39de71618 (docs: deprecate: Request.serviceWorker() (#32136))
  - [x] https://github.com/microsoft/playwright/commit/058883430740044783125df8ae2e3a3fbe9f7718 (feat: allow `URLSearchParams` and `string` as params in `APIRequestContext` (follow-up) (#32143))
  - [x] https://github.com/microsoft/playwright/commit/f8eef3897c0f522e79d321cc6398660c55ed534c (chore: move urlMatch to isomorphic (#32142))
  - [x] https://github.com/microsoft/playwright/commit/010778f6c5543d112a65d18fff34556c30bf5776 (feat(client-certificates): allow passing certificates from memory (#32210))
  - [x] https://github.com/microsoft/playwright/commit/d5a74950410feb1a4fb4745a1e58573d3ff40819 (feat(addInitScript): support cjs modules when passing both `path` and `arg` (#32240))
  - [x] https://github.com/microsoft/playwright/commit/3a75f23ea1d116a57f6a9d6bf758cf8d693eb7c3 (fix(addInitScript): require non-undefined arg to trigger commonjs module (#32282))
  - [x] https://github.com/microsoft/playwright/commit/1b220c528952dab0dbe5272df844f755173cc4d1 (chore: remove Chromium Windows proxy hacks (#31724))
  - [x] https://github.com/microsoft/playwright/commit/37eb66df10d962390cd4d5a74844c244702b591a (chore: extract performAction in recorder (#32279))
  - [x] https://github.com/microsoft/playwright/commit/abe6c04a54d6231f64201011bff7bc45b7d2e053 (chore: remove `noWaitAfter` from selectOption (#32283))
  - [x] https://github.com/microsoft/playwright/commit/3d9342aa775a65950851dd54411569cad3f30579 (chore: update removeAllListeners docs (#32305))
  - [x] https://github.com/microsoft/playwright/commit/4340d153df8d243829afb01ccfaad3999cd20ecc (chore: deprecate locator.frameLocator() (#32306))
  - [x] https://github.com/microsoft/playwright/commit/888a5b53e7972a65917fd8df81b9de537405b2b5 (docs: avoid confustion with incognito mode (#32327))
  - [x] https://github.com/microsoft/playwright/commit/ec681ca78c7ce8a3a841f2583ec2a72c205cba4a (chore: pass explicit recorder app factory (#32349))
  - [x] https://github.com/microsoft/playwright/commit/896190edbb4e4298129164706c14782c0ad71f79 (Revert feat(addInitScript): support cjs modules (#32364))
  - [x] https://github.com/microsoft/playwright/commit/b8c4a477ffe818e64ed8ea1aa33af110d840b2ab (chore(docs): fix APIResponse.headersArray() desc (#32375))
  - [x] https://github.com/microsoft/playwright/commit/b75483bbb49fd27ccb7efa93444fae162f10a413 (Revert "docs: deprecate: Request.serviceWorker() (#32136)" (#32432))
  - [x] https://github.com/microsoft/playwright/commit/446ed72878981d6c88861b3dc20820cd6ffe36a1 (docs: revert typo (#32433))
  - [x] https://github.com/microsoft/playwright/commit/9a2c60a77cdde80e4357246401af60db71fb3a4a (chore: identify largest gaps in Bidi API (#32434))
