### ISSUE TITLE
[Ports]: Backport client side changes for 1.48

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#2545]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/f0e13164d72494e161a37d2f6d6b05fddab5f4b1 (chore: split firefox and chromium bidi implementations (#32478))
  - [x] https://github.com/microsoft/playwright/commit/a8f67a42b8995d0e3f8dbf82ca755e93de7ee0b0 (docs(dotnet): fix wrong snippets (#32484))
  - [x] https://github.com/microsoft/playwright/commit/728083b435ac0d7ec379a22bf7f7edc09b416490 (chore: allow query as string in Python/.NET (#32516))
  - [x] https://github.com/microsoft/playwright/commit/e5d6ee5bd81327a26fff312ce055c7c82175483e (chore: merge fetch params on server side (#32518))
  - [x] https://github.com/microsoft/playwright/commit/48c7fb6b0624a771bfcc7a8536ec4d18d780f455 (feat(library): accept `FormData` in `fetch` (#32602))
  - [x] https://github.com/microsoft/playwright/commit/f2a974b0451db21295a1dde2f8670483d8a5697b (feat(api): add method to force garbage collection (#32383))
  - [x] https://github.com/microsoft/playwright/commit/aeb4d182f749f8185797b66f28bff6828d35b867 (feat(tracing): add .pwtrace to trace file extension (#32581))
  - [x] https://github.com/microsoft/playwright/commit/b335b00a8622db4d2599741f2f013c83af8cb926 (docs: add reference to locator strictness if or resolves to multiple elements (#32633))
  - [x] https://github.com/microsoft/playwright/commit/21d162c945e81661278b08f508c0af9fcc08e78c (feat(client-certificates): add support for proxies (#32611))
  - [x] https://github.com/microsoft/playwright/commit/f6219e6e793054a89e89868f2277f194586086ea (Revert "feat(tracing): add .pwtrace to trace file extension" (#32648))
  - [x] https://github.com/microsoft/playwright/commit/2f4acbb001f5e057de243fedc075b37bcc7719a7 (chore: use contentFrame() as a canonical locator representation (#32697))
  - [ ] https://github.com/microsoft/playwright/commit/cdcaa7fab64e13ed08b3930074f06422793ec34d (feat: routeWebSocket (#32675))
  - [x] https://github.com/microsoft/playwright/commit/418d1c0c5557c5ccabd87c440146ef9c0c5987aa (chore: allow starting recorder in traceviewer (#32741))
  - [x] https://github.com/microsoft/playwright/commit/b3a82bef46e6f704312c441eea17a6bd737c1302 (feat: do not record route calls in the trace (#32723))
  - [x] https://github.com/microsoft/playwright/commit/281eff120926203229468309452a0df2e3a7e245 (docs(trial): note that modifier keys are pressed regardless of trial option (#32734))
  - [x] https://github.com/microsoft/playwright/commit/e5433d0576ee46362e68162f811dabe0f70a900c (chore(docs): validate params/options links (#32820))
  - [x] https://github.com/microsoft/playwright/commit/a9d5c39d405735f77c2a550b713736621429e9f4 (chore: address api review for page.forceGarbageCollection (#32824))
  - [x] https://github.com/microsoft/playwright/commit/3b86a9c0e44314aee07d71d50449545329466774 (docs(markdown): parse :::note's text as children (#32510))
  - [x] https://github.com/microsoft/playwright/commit/d07f6cfc5c9fdfee7fe07e8586bcd8cd4fd5ca42 (docs: check that description has an empty line before it (#32830))
  - [x] https://github.com/microsoft/playwright/commit/bcb6860ef59a6a88f52aa98961aebc40492ba4fa (chore: fix cross browser leak tests (#32843))
  - [ ] https://github.com/microsoft/playwright/commit/a395fb22c4cd414e58a291f2b1d87aa3a3714043 (feat(routeWebSocket): address api review feedback (#32850))
  - [x] https://github.com/microsoft/playwright/commit/6bc5c9ca841818185e90710eeb8d8082d3f3ec80 (docs: release notes for 1.48 (#32857))
  - [x] https://github.com/microsoft/playwright/commit/908b0de5d4733186b82a18d44b8a735013b25efe (chore: style action list in tv mode (#32845))
