### ISSUE TITLE
[internal] 1.6 todo

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#259]
- [x] feat(proxy): enable per-context http proxy (https://github.com/microsoft/playwright/pull/4280)
- [x] fix(protocol): annotate file buffer as binary (https://github.com/microsoft/playwright/pull/4272)
- [x] feat(websocket): implement Web Sockets for Chromium & WebKit (https://github.com/microsoft/playwright/pull/4234)
- [x] feat(har): allow saving har for context (https://github.com/microsoft/playwright/pull/4214)
- [x] fix(headers): report raw request headers on Chromium (https://github.com/microsoft/playwright/pull/4207)
- [x] feat(timing): introduce resource timing (https://github.com/microsoft/playwright/pull/4204)
- [x] fix(video): make video path available in persistent profiles (https://github.com/microsoft/playwright/pull/4182)
- [x] feat: tap (https://github.com/microsoft/playwright/pull/4097)
- [x] api(videos): introduce a single recordVideo option bag (https://github.com/microsoft/playwright/pull/4309)
- [x] api(websocket): do not send websocket frames without a listener (https://github.com/microsoft/playwright/pull/4361)

**Comment by pavelfeldman** [comment]
We need a better testing fixtures to test web sockets and proxy downstream...
