### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#903]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/b79be5d98d179ea8b1a5abf7a51fcb570cc4b7e0 (feat(fetch): introduce failOnStatusCode (#8896))
  - [x] https://github.com/microsoft/playwright/commit/afae5bef5db1e0e8147a614b9933e31fc56c0076 (feat(mouse): page.mouse.wheel (#8690))
  - [x] https://github.com/microsoft/playwright/commit/5141407c6bd244a2242c37a825e8f34dcffb0390 (fix(fetch): prefix request with underscore (#8922))
  - [x] https://github.com/microsoft/playwright/commit/c58f34fb2ef7d658ed558ce42386730dee6e25e5 (feat(fetch): introduce global fetch request (#8927))
  - [x] https://github.com/microsoft/playwright/commit/14bc663742277baf36daab6626b1eee9272a9b43 (chrome: don't nest pw:api steps (#8932))
  - [x] https://github.com/microsoft/playwright/commit/2380b07f300b318f173af859a065d1fe48c17f50 (feat(fetch): introduce FetchRequest.dispose, fulfill with global fetch (#8945))
