### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#912]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/806a71a4f09c7e737adfec74ab65bf3d73fefdcd (feat(fetch): support form data and json encodings (#8975))
  - [x] https://github.com/microsoft/playwright/commit/9b0e0c22735f86e049b174bcfd3cde185284a305 (fix: restore support for slowmo connect option (#9038))
  - [ ] https://github.com/microsoft/playwright/commit/d354d14fb91f76b90b263feb92cd801e3b3d774f (chore: move Frame.waitForTimeout to the server side (#9053))
  - [x] https://github.com/microsoft/playwright/commit/79eb7744bc60c594a3d461d724c6abbea4f0a4d6 (feat(fetch): support options in playwright._newRequest (#9061))
  - [x] https://github.com/microsoft/playwright/commit/0908dc98c8d6226fa02c6a0a5fd81003dcb8e158 (chore: migrate expect(locator).toMatchText to protocol (#9117))
  - [x] https://github.com/microsoft/playwright/commit/1db41c330a7d50c1264da4a7b175861b701a105e (chore: migrate remaining expect to protocol (#9121))

**Comment by kumaraditya303** [comment]
https://github.com/microsoft/playwright/pull/8566

**Comment by mxschmitt** [comment]
> microsoft/playwright#8566

For now we want to keep it on the client side in Python and it's friends. It's more like an experiment that we moved it.

**Comment by kumaraditya303** [comment]
@mxschmitt apparently java port switched to driver based remote connection recently https://github.com/microsoft/playwright-java/pull/615
