### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-python#921]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/241411ad421e89bb50f46e8eb1ffa0abde03d210 (chore: render expect in trace viewer (#9141))
  - [x] https://github.com/microsoft/playwright/commit/cd22072685ee2c043a1955bc6b4b57e684565131 (chore: enable object-curly-spacing in ESLint (#9168))
  - [x] https://github.com/microsoft/playwright/commit/2b055b3092bd1a1073f1a4d8295458899ee454b6 (feat(api): introduce locator.waitFor (#9200))
  - [x] https://github.com/microsoft/playwright/commit/b93718daeaf1198348e2996a69cddd2bd4ed1cf8 (feat(fetch): support ignoreHTTPSErrors option (#9206))
  - [x] https://github.com/microsoft/playwright/commit/7c89bc162a60b104553c5ac4429ded9f599bacc4 (fix: leaking route handlers when times is used in Page.route (#9234))
  - [x] https://github.com/microsoft/playwright/commit/4e372dccb56cd582a07dcf627eaa7812dac8cab4 (feat(fetch): import/export storageState (#9244))
  - [x] https://github.com/microsoft/playwright/commit/235eaca34ab9e24d2a38a428ac77f0397dfafeb7 (fix(fetch): use data, form and multipart for different post data (#9248))
  - [x] https://github.com/microsoft/playwright/commit/913821f675556412594d78de7902e17087331a02 (chore: roll Electron to 12.2.1 (#9271))
